I'm sorry, but an uncaught exception occurred.

While parsing E:\renpy-6.17.6-sdk\Tragedy VN/game/script2.rpy.
ScriptError: Name u'route_aa' is defined twice: at game/script.rpy:250 and game/script2.rpy:1.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "E:\renpy-6.17.6-sdk\renpy\bootstrap.py", line 285, in bootstrap
    renpy.main.main()
  File "E:\renpy-6.17.6-sdk\renpy\main.py", line 248, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "E:\renpy-6.17.6-sdk\renpy\script.py", line 177, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "E:\renpy-6.17.6-sdk\renpy\script.py", line 451, in load_appropriate_file
    if not self.load_file(dir, fn + source, initcode):
  File "E:\renpy-6.17.6-sdk\renpy\script.py", line 320, in load_file
    self.finish_load(stmts, initcode)
  File "E:\renpy-6.17.6-sdk\renpy\script.py", line 392, in finish_load
    node.filename, node.linenumber))
ScriptError: Name u'route_aa' is defined twice: at game/script.rpy:250 and game/script2.rpy:1.

Windows-7-6.1.7601-SP1
Ren'Py 6.17.6.512
 
